export { FirstPage } from './Screens/FirstPage'
export { SecondPage } from './Screens/SecondPage'
export { default as Login } from './Screens/Login'
export { default as Signup } from './Screens/Signup'
export { default as Home } from './Screens/Home'